# Generated by Django 5.2.3 on 2025-08-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role_alter_customuser_gender_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
