# Generated by Django 5.2.3 on 2025-08-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0007_alter_glasses_store'),
        ('users', '0005_remove_customuser_age_remove_customuser_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
