# Generated by Django 5.2.3 on 2025-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.CharField(max_length=100, unique=True)),
                ('material', models.CharField(max_length=100)),
                ('rim', models.CharField(max_length=50)),
                ('shape', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('frame_width', models.IntegerField()),
                ('bridge', models.IntegerField()),
                ('lens_width', models.IntegerField()),
                ('lens_height', models.IntegerField()),
                ('temple_length', models.IntegerField()),
            ],
        ),
    ]
