# Generated by Django 5.2.3 on 2025-06-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasses',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='glasses_models/'),
        ),
    ]
