# Generated by Django 5.2.3 on 2025-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0002_glasses_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='glasses',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Red', 'Red'), ('Green', 'Green'), ('Purple', 'Purple'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Gold', 'Gold'), ('Olive', 'Olive'), ('White', 'White'), ('Pink', 'Pink'), ('Silver', 'Silver'), ('Beige', 'Beige'), ('Peach', 'Peach')], default='Black', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glasses',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='glasses',
            name='tone',
            field=models.CharField(choices=[('Dark', 'Dark'), ('Medium', 'Medium'), ('Light', 'Light')], default='Medium', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glasses',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex'), ('Kids', 'Kids')], max_length=10),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='material',
            field=models.CharField(choices=[('Acetate', 'Acetate'), ('Plastic', 'Plastic'), ('Metal', 'Metal'), ('Stainless Steel', 'Stainless'), ('Titanium', 'Titanium'), ('TR90', 'Tr90'), ('Mixed', 'Mixed'), ('Carbon Fiber', 'Carbon'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='shape',
            field=models.CharField(choices=[('Rectangle', 'Rectangle'), ('Square', 'Square'), ('Round', 'Round'), ('Oval', 'Oval'), ('Cat-Eye', 'Cat Eye'), ('Aviator', 'Aviator'), ('Geometric', 'Geometric'), ('Browline', 'Browline'), ('Rimless', 'Rimless'), ('Wayfarer', 'Wayfarer'), ('Butterfly', 'Butterfly'), ('Shield', 'Shield'), ('Clubmaster', 'Clubmaster'), ('Hexagonal / Octagonal', 'Hexagonal'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], max_length=20),
        ),
    ]
