# Generated by Django 5.2.3 on 2025-08-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0003_glasses_color_glasses_price_glasses_tone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='glasses_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('glasses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='glasses.glasses')),
            ],
        ),
    ]
