# Generated by Django 5.2.3 on 2025-08-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0004_glassesimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Purpose',
                'verbose_name_plural': 'Purposes',
            },
        ),
        migrations.CreateModel(
            name='GlassesPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glasses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasses.glasses')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasses.purpose')),
            ],
            options={
                'verbose_name': 'Glasses-Purpose',
                'verbose_name_plural': 'Glasses-Purposes',
                'unique_together': {('glasses', 'purpose')},
            },
        ),
        migrations.AddField(
            model_name='glasses',
            name='purposes',
            field=models.ManyToManyField(related_name='glasses', through='glasses.GlassesPurpose', to='glasses.purpose'),
        ),
    ]
