# Generated by Django 5.2.3 on 2025-08-17 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0005_purpose_glassespurpose_glasses_purposes'),
        ('users', '0005_remove_customuser_age_remove_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glasses',
            name='bridge',
        ),
        migrations.RemoveField(
            model_name='glasses',
            name='frame_id',
        ),
        migrations.RemoveField(
            model_name='glasses',
            name='frame_width',
        ),
        migrations.RemoveField(
            model_name='glasses',
            name='lens_height',
        ),
        migrations.RemoveField(
            model_name='glasses',
            name='lens_width',
        ),
        migrations.RemoveField(
            model_name='glasses',
            name='rim',
        ),
        migrations.RemoveField(
            model_name='glasses',
            name='temple_length',
        ),
        migrations.AddField(
            model_name='glasses',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glasses',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glasses', to='users.store'),
        ),
    ]
