# Generated by Django 5.2.3 on 2025-08-17 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0006_remove_glasses_bridge_remove_glasses_frame_id_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glasses', to='stores.store'),
        ),
    ]
